"""Generate a SLURM sweep from a base config + a grid of overrides.

Usage
-----
    python sweep.py --config configs/mnist_flat.yaml \\
        --name mnist_diffusion \\
        --grid train.lam=1e-3,3e-3,1e-2 \\
        --grid estimator.k=32,64,128 \\
        --grid data.seed=0,1,2 \\
        --partition gpu --account myacct --time 02:00:00 --mem 16G

Writes
  - cluster/jobs/<name>/run_<i>.sh   one SLURM script per grid point
  - cluster/jobs/<name>/submit_all.sh  sbatch's all of them

Grid values are comma-separated; multiple --grid flags combine as a Cartesian
product. Any leaf key of the config may be overridden (data./model./train./
estimator.). Each job runs:

    python run.py --config <base> --out <results> --device cuda <overrides>
"""

import argparse
import itertools
import os
import re
import shlex
import sys
from pathlib import Path

repo_root = Path(__file__).resolve().parent
sys.path.insert(0, str(repo_root))

from Utils.config import load_config, to_dict  # noqa: E402


TEMPLATE = repo_root / "cluster" / "template.slurm"


def parse_grid(specs: list[str]) -> dict[str, list[str]]:
    grid: dict[str, list[str]] = {}
    for spec in specs:
        if "=" not in spec or ("," not in spec and "=" not in spec):
            raise SystemExit(
                f"Invalid --grid entry {spec!r}; expected 'path.to.key=val1,val2,...'"
            )
        key, _, vals = spec.partition("=")
        key = key.strip()
        if not re.match(r"^(data|model|train|estimator)\.[A-Za-z0-9_]+$", key):
            raise SystemExit(
                f"Invalid grid key {key!r}; must start with data./model./train./estimator. "
                "(update Utils/config.py to add new configurable keys)"
            )
        values = [v.strip() for v in vals.split(",") if v.strip()]
        if not values:
            raise SystemExit(f"Empty value list for grid key {key!r}")
        grid[key] = values
    return grid


def render_job(name: str, args_str: str, opts) -> str:
    subs = {
        "JOBNAME": name,
        "PARTITION": opts.partition,
        "ACCOUNT": opts.account,
        "CPUS": str(opts.cpus),
        "MEM": opts.mem,
        "TIME": opts.time,
        "LOGDIR": str((repo_root / "cluster" / "logs" / name).resolve()),
        "CONTAINER": opts.container,
        "REPO": str(repo_root),
        "ARGS": args_str,
    }
    text = TEMPLATE.read_text(encoding="utf-8")
    for k, v in subs.items():
        text = text.replace(f"__{k}__", v)
    if not opts.account:
        text = "\n".join(
            line for line in text.splitlines()
            if not line.startswith("#SBATCH --account=")
        )
    return text


def main(argv=None) -> None:
    ap = argparse.ArgumentParser(description="Generate SLURM sweep jobs")
    ap.add_argument("--config", required=True, help="Base YAML config")
    ap.add_argument("--name", required=True, help="Sweep name (job prefix + dir name)")
    ap.add_argument("--grid", action="append", default=[],
                    help="Grid axis: key=v1,v2,... (repeatable, Cartesian product)")
    ap.add_argument("--results-dir", default="results", help="--out passed to run.py")
    ap.add_argument("--device", default="cuda")
    # SLURM knobs (edit per cluster; see cluster/README.md)
    ap.add_argument("--partition", default="gpu")
    ap.add_argument("--account", default="")
    ap.add_argument("--cpus", type=int, default=8)
    ap.add_argument("--mem", default="16G")
    ap.add_argument("--time", default="02:00:00")
    ap.add_argument(
        "--container",
        default="/share_zeta/Proxy-Sim/guillermo.carrillo/envs/ICA_v4.sif",
        help="Singularity container path (if set, jobs use singularity exec --nv)",
    )
    args = ap.parse_args(argv)

    cfg = load_config(args.config)
    cfg.name = cfg.name or cfg.data.experiment

    grid = parse_grid(args.grid)
    keys = list(grid)
    combos = list(itertools.product(*[grid[k] for k in keys])) if keys else [()]

    name = args.name
    jobs_dir = repo_root / "cluster" / "jobs" / name
    jobs_dir.mkdir(parents=True, exist_ok=True)

    job_scripts = []
    for i, combo in enumerate(combos):
        override_pairs = []
        for k, v in zip(keys, combo):
            override_pairs += [f"--{k}", v]
        overrides_str = " ".join(shlex.quote(p) for p in override_pairs)
        args_str = (
            f"--config {args.config} "
            f"--out {args.results_dir} --device {args.device} {overrides_str}".strip()
        )
        script = render_job(name, args_str, args)
        path = jobs_dir / f"run_{i:04d}.sh"
        path.write_text(script, encoding="utf-8")
        job_scripts.append(path)

    submit = jobs_dir / "submit_all.sh"
    submit.write_text(
        "#!/bin/bash\n# Generated by sweep.py; edit --partition/--account for your cluster.\n"
        + "\n".join(f"sbatch {p.name}" for p in job_scripts)
        + "\n",
        encoding="utf-8",
    )
    submit.chmod(0o755)

    print(f"Wrote {len(job_scripts)} jobs to {jobs_dir}")
    print(f"Resolved config (base):")
    for block, d in to_dict(cfg).items():
        print(f"  {block}: {d}")
    print(f"Grid keys: {keys}")
    print(f"Submit with: sbatch {submit.name}  (from {jobs_dir})")


if __name__ == "__main__":
    main()